### ISSUE TITLE
Stop showing bonus games button not funtional

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#249]
@cgladue I was just on the site and I moved the little button over to Stop showing the bonus games screen any more, but it does NOT change the preferences in the Manage Account screen and I still see them when I click on another Shop Now button.

It DOES work if I am in the Manage Account page and uncheck the box and Save Preferences.

When you do get it to work from the game interstitial page, please have the little green confirmation notification that shows up to say it has been changed to read, "Your preference has been saved, if you would like to change it back at any time, visit "Manage Account" section." If is it possible to make Manage Account clickable to "../account/myprofile" let's do that too. 
 
![Screenshot (July 8, 2019 5_48 PM)](https://user-images.githubusercontent.com/28393235/60845163-7bcba780-a1a9-11e9-83e7-9e51a108967a.png)

**Comment by cgladue** [comment]
hmm, i am looking at this and to me to dosnt seem like this functionality was ever implemented by chris ... thats his side of things and i dont see any reference to where it would save the selection :(

**Comment by robgpeak** [comment]
@ChrisASearles can you please look into this.

**Comment by cgladue** [comment]
@ChrisASearles let me know if you need anything like a controller action for this or something ... i looked and i dont see anywhere that it may have gone before, so i am guessing it was just a placeholder ?

**Comment by ChrisASearles** [comment]
@cgladue Wasn't an oversight. I was told that games had been added to the site and they needed to be made to look consistent with the rest of the site. The rest of the functionality - including asynchronous calls to the server - had already been built (including a checkbox to opt out of games) and I wasn't provided with any information on what had been done on the front-end, what server-side logic that had been added to support new functionality, or any additional functionality that I was being asked to build so I assumed someone else was handling that portion.

@robgpeak I don't know who's responsibility it is, but in the future it would be extremely helpful (especially after not being involved in development for such a long time) for someone to provide some sort of detail on the functionality I'm being asked to build, the history of how it got to where it is, and what the acceptance criteria is for my work to be approved and integrated into the mainline. As my responsibilities have always been limited to the front-end, detail on the server-side logic that was built to support any front-end work that's being requested would be helpful as well.

A clear understanding of what I'm being asked to do would go a long way to reducing the frequency and quantity of bugs that end up in production code and reduce development time and costs.

@cgladue I just spent a half hour re-familiarizing myself with the site to try to get this done. If the intent is to make this an asynchronous call, I need an endpoint to call. Currently the profile page is submitted in whole as a POST to /account/saveProfile which requires a CompLinksWeb.Models.User object in the body of the post. Please let me know when there is a suitable endpoint for me to call from the front-end when that toggle switch is updated and I can take care of the front-end logic.

**Comment by robgpeak** [comment]
@cgladue I am assuming this is an issue that you will be able to fix without Chris once the new test site becomes the live site because as it is now on the current live site, it was/is and Angular issue.

I know there are a couple of little things left to do on the new site before putting it live.  Do you have a time frame?

**Comment by cgladue** [comment]
I am hoping this week.   Once you give me the go ahead.  Ill get back to
you with more to test and yes i wont need chris

**Comment by robgpeak** [comment]
You have the go-ahead right now as long as everything is working and
functioning properly. So if there's any last minute testing that you go
through and see needs attending to let me know and I'll look at it

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
@robgpeak this is working now...

**Comment by robgpeak** [comment]
As I mentioned in the other post I was not able to turn off the
functionality. Meaning I click the checkbox to let it show me the bonus
games but when I hit save I got an error message.

**Comment by cgladue** [comment]
looking at it now, i dont get an error on my account so checking whats different with you ...

**Comment by cgladue** [comment]
i think this was fixed with one of the other updates i did can you try on test

**Comment by robgpeak** [comment]
no it's not fixed. Have a look https://youtu.be/EeTZOjbmTdg

Thanks,

Rob

**Sent from my phone

**Comment by cgladue** [comment]
ok, gotcha yea seems not to do what its supposed to i thought it was related to one of the other things nevermind

**Comment by cgladue** [comment]
hah! i knew what i did wrong dumbass (me not you lol)  try it again when you can

**Comment by robgpeak** [comment]
Working as expected.  Let's launch it on Xclub tomorrow morning at 8:00 am
